### ISSUE TITLE
分离dev和pro环境，dev环境需要有热更新功能

### ISSUE THREAD

**Issue by frankshin** [frankshin/public-html-layout#1]

**Comment by 645605935** [comment]
你好，dev环境热更新功能啥 时候可以用，期待你的这个版本

**Comment by 645605935** [comment]
你好，dev环境热更新功能现在可以用了吗，有没有操作说明文档？

**Comment by frankshin** [comment]
> 你好，dev环境热更新功能现在可以用了吗，有没有操作说明文档？

你好，可以，在最新的v1.0.6版本，文档见readme

**Comment by 645605935** [comment]
你好，方便加下我的QQ：645605935 吗，文档写的有点简单，我还是没太看明白




------------------ 原始邮件 ------------------
发件人: "frankshin"<notifications@github.com>; 
发送时间: 2019年7月23日(星期二) 上午10:12
收件人: "frankshin/public-html-layout"<public-html-layout@noreply.github.com>; 
抄送: "火星人"<645605935@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [frankshin/public-html-layout] 分离dev和pro环境，dev环境需要有热更新功能 (#1)



 
你好，dev环境热更新功能现在可以用了吗，有没有操作说明文档？
  
你好，可以，在最新的v1.0.6版本，文档见readme

**Comment by 645605935** [comment]
我开发的时候页面应该如何访问呢



------------------ 原始邮件 ------------------
发件人: "frankshin"<notifications@github.com>; 
发送时间: 2019年7月23日(星期二) 上午10:12
收件人: "frankshin/public-html-layout"<public-html-layout@noreply.github.com>; 
抄送: "火星人"<645605935@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [frankshin/public-html-layout] 分离dev和pro环境，dev环境需要有热更新功能 (#1)



 
你好，dev环境热更新功能现在可以用了吗，有没有操作说明文档？
  
你好，可以，在最新的v1.0.6版本，文档见readme

**Comment by frankshin** [comment]
> 我开发的时候页面应该如何访问呢
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "frankshin"<notifications@github.com>; 发送时间: 2019年7月23日(星期二) 上午10:12 收件人: "frankshin/public-html-layout"<public-html-layout@noreply.github.com>; 抄送: "火星人"<645605935@qq.com>; "Comment"<comment@noreply.github.com>; 主题: Re: [frankshin/public-html-layout] 分离dev和pro环境，dev环境需要有热更新功能 (#1) 你好，dev环境热更新功能现在可以用了吗，有没有操作说明文档？ 你好，可以，在最新的v1.0.6版本，文档见readme — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

devserver里有配端口号（localhost:9000），后面我会更新一版，加上自动打开页面功能

**Comment by 645605935** [comment]
你好，我使用npm run prod打包，报这个错，是什么原因造成的呢？




------------------ 原始邮件 ------------------
发件人: "frankshin"<notifications@github.com>; 
发送时间: 2019年7月23日(星期二) 上午10:53
收件人: "frankshin/public-html-layout"<public-html-layout@noreply.github.com>; 
抄送: "火星人"<645605935@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [frankshin/public-html-layout] 分离dev和pro环境，dev环境需要有热更新功能 (#1)



 
我开发的时候页面应该如何访问呢
 …
 ------------------ 原始邮件 ------------------ 发件人: "frankshin"notifications@github.com; 发送时间: 2019年7月23日(星期二) 上午10:12 收件人: "frankshin/public-html-layout"public-html-layout@noreply.github.com; 抄送: "火星人"645605935@qq.com; "Comment"comment@noreply.github.com; 主题: Re: [frankshin/public-html-layout] 分离dev和pro环境，dev环境需要有热更新功能 (#1) 你好，dev环境热更新功能现在可以用了吗，有没有操作说明文档？ 你好，可以，在最新的v1.0.6版本，文档见readme — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
  
devserver里有配端口号（localhost:9000），后面我会更新一版，加上自动打开页面功能
 
&mdash;

**Comment by frankshin** [comment]
> 你好，我使用npm run prod打包，报这个错，是什么原因造成的呢？
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "frankshin"<notifications@github.com>; 发送时间: 2019年7月23日(星期二) 上午10:53 收件人: "frankshin/public-html-layout"<public-html-layout@noreply.github.com>; 抄送: "火星人"<645605935@qq.com>; "Comment"<comment@noreply.github.com>; 主题: Re: [frankshin/public-html-layout] 分离dev和pro环境，dev环境需要有热更新功能 (#1) 我开发的时候页面应该如何访问呢 … ------------------ 原始邮件 ------------------ 发件人: "frankshin"notifications@github.com; 发送时间: 2019年7月23日(星期二) 上午10:12 收件人: "frankshin/public-html-layout"public-html-layout@noreply.github.com; 抄送: "火星人"645605935@qq.com; "Comment"comment@noreply.github.com; 主题: Re: [frankshin/public-html-layout] 分离dev和pro环境，dev环境需要有热更新功能 (#1) 你好，dev环境热更新功能现在可以用了吗，有没有操作说明文档？ 你好，可以，在最新的v1.0.6版本，文档见readme — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread. devserver里有配端口号（localhost:9000），后面我会更新一版，加上自动打开页面功能 &mdash; You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

加你了
